table 'Order Table'
	lineageTag: ec1a67ee-6fd9-44ea-a976-32a311d2c322

	column 'Time Period'
		dataType: string
		lineageTag: 540ed899-cde5-4405-9ed5-19605949508b
		summarizeBy: none
		sourceColumn: Time Period
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: aa8b097f-d6a8-4a12-b77c-9522d57c059b
		summarizeBy: none
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	partition 'Order Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8kktLlYoyUjMUzAyUcjILy0qVtJRMlSK1YlWMlR41DBZwUjBJbESJGgEFjQCC5rCBI3BgqZgQXOYoAmK9vDU1GyQqCmSfhO4qBlY1L8stUjBUME3P68kAyhorhQbCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Time Period" = _t, #"Sort Order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Time Period", type text}, {"Sort Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

