table Know_AWN
	lineageTag: 2ea457a5-8cca-4e02-9f26-0032d5007a07

	column ID
		dataType: int64
		formatString: 0
		lineageTag: d62cc7f3-02b7-4429-ac9d-fc2d7229709a
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 728ca5b4-3609-4c0f-80b7-fd3f25a09875
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'How did you learn about AWN?'
		dataType: string
		lineageTag: 11588f1d-0a97-4223-952f-d4d31f6bb8b3
		summarizeBy: none
		sourceColumn: How did you learn about AWN?

		annotation SummarizationSetBy = Automatic

	partition Know_AWN = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\brohlm\Autodesk\AWN - General\Impact Measurement\Annual Member Survey\2024-10\Autodesk Women's Network Impact Measurement Survey FY25(1-105).xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"ID", Int64.Type}, {"Start time", type datetime}, {"Completion time", type datetime}, {"Email", type text}, {"Name", type text}, {"Last modified time", type any}, {"How did you learn about AWN?", type text}, {"What motivated you to sign up with AWN?", type text}, {"AWN has supported my personal goal(s) since I joined.", type text}, {"Based on your answer above, can you share an event or program that positively or negatively impacted your journey?", type text}, {"How has your involvement in AWN impacted your sense of belonging and inclusion within the company?", type text}, {"How might AWN contribute to increase your sense of belonging and inclusion at Autodesk?", type text}, {"What if any additional support or resources would you like to see offered by AWN? ", type text}, {"What would you like to see AWN focus on in FY26?", type text}, {"If you haven't participated in any activities to date please indicate why.", type text}, {"What do you feel AWN is doing well?", type text}, {"How might we improve to better meet your needs?", type text}, {"Can we reach out to you if we have additional follow up questions?", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"ID", "Email", "How did you learn about AWN?"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Other Columns", {{"How did you learn about AWN?", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "How did you learn about AWN?"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"How did you learn about AWN?", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([#"How did you learn about AWN?"] <> ""))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

