table Add_Resources
	lineageTag: e2751335-bef9-4d16-a1a1-aae9ac986f01

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 2e34ea93-453a-4a6a-b096-ea1dc341b5fe
		summarizeBy: sum
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 06c44247-e8b2-4f7d-9617-8a4df2990ad6
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'What if any additional support or resources would you like to see offered by AWN? '
		dataType: string
		lineageTag: c535fc84-3959-4833-a5b7-9e24bdf41a22
		summarizeBy: none
		sourceColumn: "What if any additional support or resources would you like to see offered by AWN? "

		annotation SummarizationSetBy = Automatic

	partition Add_Resources = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\brohlm\Autodesk\AWN - General\Impact Measurement\Annual Member Survey\2024-10\Autodesk Women's Network Impact Measurement Survey FY25(1-105).xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"ID", Int64.Type}, {"Start time", type datetime}, {"Completion time", type datetime}, {"Email", type text}, {"Name", type text}, {"Last modified time", type any}, {"How did you learn about AWN?", type text}, {"What motivated you to sign up with AWN?", type text}, {"AWN has supported my personal goal(s) since I joined.", type text}, {"Based on your answer above, can you share an event or program that positively or negatively impacted your journey?", type text}, {"How has your involvement in AWN impacted your sense of belonging and inclusion within the company?", type text}, {"How might AWN contribute to increase your sense of belonging and inclusion at Autodesk?", type text}, {"What if any additional support or resources would you like to see offered by AWN? ", type text}, {"What would you like to see AWN focus on in FY26?", type text}, {"If you haven't participated in any activities to date please indicate why.", type text}, {"What do you feel AWN is doing well?", type text}, {"How might we improve to better meet your needs?", type text}, {"Can we reach out to you if we have additional follow up questions?", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"ID", "Email", "What if any additional support or resources would you like to see offered by AWN? "}),
				    #"Split Column by Delimiter1" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Other Columns", {{"What if any additional support or resources would you like to see offered by AWN? ", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "What if any additional support or resources would you like to see offered by AWN? "),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"What if any additional support or resources would you like to see offered by AWN? ", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each ([#"What if any additional support or resources would you like to see offered by AWN? "] <> null and [#"What if any additional support or resources would you like to see offered by AWN? "] <> ""))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

